/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendGiftRouteImport } from './routes/api/send-gift'
import { Route as ApiGetStoreRouteImport } from './routes/api/get-store'
import { Route as ApiItemImageIdRouteImport } from './routes/api/item-image.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendGiftRoute = ApiSendGiftRouteImport.update({
  id: '/api/send-gift',
  path: '/api/send-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetStoreRoute = ApiGetStoreRouteImport.update({
  id: '/api/get-store',
  path: '/api/get-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemImageIdRoute = ApiItemImageIdRouteImport.update({
  id: '/api/item-image/$id',
  path: '/api/item-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/get-store': typeof ApiGetStoreRoute
  '/api/send-gift': typeof ApiSendGiftRoute
  '/api/item-image/$id': typeof ApiItemImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/get-store': typeof ApiGetStoreRoute
  '/api/send-gift': typeof ApiSendGiftRoute
  '/api/item-image/$id': typeof ApiItemImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/get-store': typeof ApiGetStoreRoute
  '/api/send-gift': typeof ApiSendGiftRoute
  '/api/item-image/$id': typeof ApiItemImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/get-store' | '/api/send-gift' | '/api/item-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/get-store' | '/api/send-gift' | '/api/item-image/$id'
  id:
    | '__root__'
    | '/'
    | '/api/get-store'
    | '/api/send-gift'
    | '/api/item-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGetStoreRoute: typeof ApiGetStoreRoute
  ApiSendGiftRoute: typeof ApiSendGiftRoute
  ApiItemImageIdRoute: typeof ApiItemImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-gift': {
      id: '/api/send-gift'
      path: '/api/send-gift'
      fullPath: '/api/send-gift'
      preLoaderRoute: typeof ApiSendGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-store': {
      id: '/api/get-store'
      path: '/api/get-store'
      fullPath: '/api/get-store'
      preLoaderRoute: typeof ApiGetStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/item-image/$id': {
      id: '/api/item-image/$id'
      path: '/api/item-image/$id'
      fullPath: '/api/item-image/$id'
      preLoaderRoute: typeof ApiItemImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGetStoreRoute: ApiGetStoreRoute,
  ApiSendGiftRoute: ApiSendGiftRoute,
  ApiItemImageIdRoute: ApiItemImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
